language: node_js
os:
- linux
- osx
node_js:
- 4
- 6
- stable
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email:
    secure: G9oaCuvGo7fTkeHFOFYwgCEUUAIRgNW/V6ANYotZsov2U2a5H2eBvttLoYB/Q/GMgYqRKg9ptQpdcJG4q8/Qx3aLKjpFMRzcbFpaBCzEwmoHj7oJv+F4BUygZ3LabIRJ1uGC9htBeghInLRjOcxenfqKNSv/3PMojFLEa2oiFTAJwznRVKiWqzqu27uu/DjEE3U256HvIOK6WqoXiuXwmmxBrD9fSKuC+5SddmppVGp30FLUxpvZwvVCQbAogEUqHWzeOv1n0fG4iJKU9n76/L9hmqAztPZYuMbZ6Xi6ivI7tshueeQpoNSb4MCYHqbyzxNcl3DHtuLt1t87BiDSRShlQz5LGSlADPx7T3s1yxmCR+yy/yF67/04wGlw+ioigyPb4ZMd4XvaNRLPTcX/ovtN0JQZ7SQY1JVcsWLe58e9m3KKsgoD5c7SihKTGzlCodfxo+NpfCfVJpRvqylLEkmS6+jO792DCoFoMHvDyVmPoopX/fwzLmflshKc748SJUcrGCGNundnW6BPIWG1lwVUnASkwPD4l22rOROk3+99mAw5w9T8OPKSsghcMU7CxsNJUcbnLOFCasry1rB7L12WLoFVj9juSeZtWL9WENxpm4Au8VdRc0dIUwtHAgVm6RQhNtfotNqd+zwGPnNc+6I/jOhd6KCpTo5Aw0qakxQ=
  api_key:
    secure: PAQmFvAHeUWAHeRd4lWCQArPDllhRQ1fnp/s8/xy1wUQUWK6YX3RZ74tl3FsliLn6FUsfmritY9ZuKyF1MgQ+tqWKlQe7qHR5D4oNetjrQJY9frGKBn5MIc+Z+IdCxWE15pBX/29HfOj7BJUkoMzH/9UYAjRyUfMBoBWyYuOAS/m6sacfRPQOa80bVn1kkCjEu9N1x/dhISqlbyvzqljVqyo32SKiFILfmTli+1iVJMmLlo0Dcf/5dZqfyzldEQ3nLfJ+QH2f0bdwfMj7Dnc2tHJC69InNtoSzKg6y9EA2m+8+98Gi04ZWS2pXo5iksdJ4fGE6Vr1vVaCnQc/ylrMPYgeFcfqBGU8hfVFYIZHKj6i1JIdWRwg1mDIqPwCCEMSc3lF6j1OSCzBmCraH7iEZdeGeylJtexjGEEv+NWdUhwbjGrq+xtTLIFi5r3eBIABD3rc2KvKDf94i75tmwMlXcmpEyUcGsv2+PnaIKYB5EijFYkYbF7J1nMwSuBAIbf6LlaBGYsC08iwaSubJ4HasqAmhyowOO+e+ZUeLl6sZQXDMms89i9YRiWMG4IQKgzDVAYzn0MusP6QQQrn54R9md94RGox3votFFWL5ltPDQkGj75cqnSMpm45f44P4OyA6Fi98Pyd4hZlC3Vi+LFWH4+LHppL4XvdcdeIg39hO8=
